build:
  test:
    image: golang:1.5
    environment:
      - CGO_ENABLED=0
      - GO15VENDOREXPERIMENT=1
    commands:
      - go vet
      - go test
      - go build -ldflags "-s -w -X main.version=$DRONE_BUILD_NUMBER"
    when:
      event: push

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/gitter
    tag: latest

plugin:
  name: Gitter
  desc: Send build status notifications via Gitter
  type: notify
  image: plugins/gitter
  labels:
    - chat
    - messaging
    - gitter
