build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go get
    - go build
    - go test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-gitter
    when:
      branch: master

plugin:
  name: Gitter
  desc: Send status updates to Gitter when your build completes.
  type: notify
  image: plugins/drone-gitter
  labels:
    - notify
    - gitter
    - chat
